version: "2"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - afterglow-judge-sandbox

linters:
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  exclusions:
    rules:
      - linters: [errcheck]
        path: _test\.go
      - linters: [revive]
        text: "exported:|package-comments:"

settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter
      - name: redefines-builtin-id

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
